### ISSUE TITLE
No generator

### ISSUE THREAD

**Issue by ellis2323** [davidwallacejackson/vue-cli-plugin-unit-karma#1]
I'm trying to set a projet with vuecli 3.0 beta 6:

```
 prompt$ vue create myapp
 prompt$ cd myapp
 prompt$ vue add vue-cli-plugin-unit-karma
```

Error: Plugin vue-cli-plugin-unit-karma does not have a generator.
    at invoke (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:80:11)
    at module.exports.args (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:152:10)
    at add (/usr/local/lib/node_modules/@vue/cli/lib/add.js:29:3)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

there's this annoying message but it seems functional

**Comment by ellis2323** [comment]
Works better with vue-cli beta 7: only a warning message
No more Error message

**Comment by davidwallacejackson** [comment]
New version (0.5.0) has a generator! Please let me know if anything's still wrong with it.
