### ISSUE TITLE
Plugin does not work with latest version of vue-cli

### ISSUE THREAD

**Issue by scottbedard** [davidwallacejackson/vue-cli-plugin-unit-karma#9]
With the latest version of vue-cli, it appears that the webpack config is not being passed to karma anymore. The `test:unit` command fails with the following output...

```
yarn run v1.9.4
$ vue-cli-service test:unit
07 02 2019 10:52:59.549:ERROR [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?

START:
07 02 2019 10:52:59.592:ERROR [karma]: Error: Found 1 load error
    at Server.webServer.listen (/code/vue-karma-bug/node_modules/karma/lib/server.js:170:27)
    at Object.onceWrapper (events.js:273:13)
    at Server.emit (events.js:187:15)
    at emitListeningNT (net.js:1320:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:33720) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
Karma has exited with 1
 ERROR  1
error Command failed with exit code 1.
```

See reproduction repo at https://github.com/scottbedard/vue-karma-bug

Any help with this issue would be appreciated!

> **Update:** Just investigated this a bit, and it appears that things stopped working with vue-cli 3.1.0

**Comment by tushararora** [comment]
@scottbedard 

Here is a new plugin I created since this repository has become inactive now: https://github.com/tushararora/vue-cli-plugin-unit-karmajs
